[tool.poetry]
name = "lambdata-pt5-primefactorx01"
version = "0.1.0"
description = ""
authors = ["Erik Seguinte <erikseguinte@me.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
numpy = "^1.18.4"
category-encoders = "^2.2.2"
xgboost = "^1.0.2"
lightgbm = "^2.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
